In [1]:
import pandas as pd

In [ ]:
court_df = pd.read_excel('./data/Sample Data.xlsx', header=4)
court_df.head(10)

In [6]:
column_name = [
    "line",
    "date_dd",
    "date_mon",
    "date_yyyy",
    "caseid_type",
    "caseid_no",
    "filed_dd",
    "filed_mon",
    "filed_yyyy",
    "original_court",
    "original_code",
    "original_number",
    "original_year",
    "case_type",
    "judge_1",
    "judge_2",
    "judge_3",
    "judge_4",
    "judge_5",
    "judge_6",
    "judge_7",
    "comingfor",
    "outcome",
    "reason_adj",
    "next_dd",
    "next_mon",
    "next_yyyy",
    "male_applicant",
    "female_applicant",
    "organization_applicant",
    "male_defendant",
    "female_defendant",
    "organization_defendant",
    "legalrep",
    "applicant_witness",
    "defedant_witness",
    "custody",
    "other_details"]

In [8]:
court_data = pd.read_excel('./data/Sample Data.xlsx', header=4, names=column_name)
court_data.head()

,line,date_dd,date_mon,date_yyyy,caseid_type,caseid_no,filed_dd,filed_mon,filed_yyyy,original_court,...,firstparty_f,firstparty_org,secondparty_m,secondparty_f,secondparty_o,legalrep,p_witness,d_witness,custody,other_details
0,NaN,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
1,NaN,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,1.0,0.0,NaN
2,NaN,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
3,NaN,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
4,NaN,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,...,NaN,1.0,NaN,2.0,NaN,No,NaN,NaN,2.0,NaN

In [10]:
court_data.drop(columns=['line'], inplace=True)
court_data.head()

,date_dd,date_mon,date_yyyy,caseid_type,caseid_no,filed_dd,filed_mon,filed_yyyy,original_court,original_code,...,firstparty_f,firstparty_org,secondparty_m,secondparty_f,secondparty_o,legalrep,p_witness,d_witness,custody,other_details
0,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
1,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,1.0,0.0,NaN
2,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
3,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
4,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,NaN,...,NaN,1.0,NaN,2.0,NaN,No,NaN,NaN,2.0,NaN

In [13]:
court_data['date_today'] = court_data[["date_dd", "date_mon", "date_yyyy"]].astype(str).apply(lambda x: '-'.join(x), axis=1)

In [ ]:
court_data['next_date'] = court_data[["next_dd", "next_mon", "next_yyyy"]].astype(str).apply(lambda x: '-'.join(x), axis=1)
court_data['next_date'] = pd.to_datetime(court_data['next_date'])

court_data.to_csv('court_data.csv', index=False)

In [15]:
court_data['date_today'] = pd.to_datetime(court_data['date_today'], format='%d-%b-%Y')

In [17]:
court_data.drop(columns=["date_dd", "date_mon", "date_yyyy"])

,caseid_type,caseid_no,filed_dd,filed_mon,filed_yyyy,original_court,original_code,original_number,original_year,case_type,...,firstparty_org,secondparty_m,secondparty_f,secondparty_o,legalrep,p_witness,d_witness,custody,other_details,date_today
0,QRCR,E642,3,Apr,2023,NaN,NaN,NaN,NaN,"Burglary, housebreaking, entering dwelling-hou...",...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
1,QRCR,E1411,31,Oct,2022,NaN,NaN,NaN,NaN,"Burglary, housebreaking, entering dwelling-hou...",...,1.0,1.0,NaN,NaN,No,NaN,1.0,0.0,NaN,2023-04-03
2,QRCR,E649,3,Apr,2023,NaN,NaN,NaN,NaN,Possession of narcotic drugs and psychotropic ...,...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
3,QRCR,E638,3,Apr,2023,NaN,NaN,NaN,NaN,"Grievous harm, maim, assault causing actual bo...",...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
4,QRCRMISC,E109,3,Apr,2023,NaN,NaN,NaN,NaN,Criminal Miscellaneous Application,...,1.0,NaN,2.0,NaN,No,NaN,NaN,2.0,NaN,2023-04-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,QRSUCCMISC,E085,19,Apr,2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,...,NaN,1.0,NaN,NaN,Yes,NaN,NaN,0.0,NaN,2023-04-28
2153,QRSUCCMISC,E074,6,Apr,2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,...,NaN,NaN,NaN,NaN,No,NaN,NaN,0.0,NaN,2023-04-28
2154,QRCC,E216,28,Apr,2023,NaN,NaN,NaN,NaN,Liquidated Claim,...,NaN,2.0,1.0,NaN,Yes,NaN,NaN,0.0,Certificate of urgency activity auto-created,2023-04-28
2155,QRELCMISC,E009,27,Apr,2023,NaN,NaN,NaN,NaN,Environmental and Land Miscellaneous,...,NaN,NaN,1.0,NaN,No,NaN,NaN,0.0,Certificate of urgency activity auto-created,2023-04-28
2156,QRCC,24,24,Jan,2020,NaN,NaN,NaN,NaN,Commercial Suits,...,NaN,1.0,NaN,NaN,Yes,NaN,NaN,0.0,Certificate of urgency activity auto-created,2023-04-28

In [16]:
court_data.head()

,date_dd,date_mon,date_yyyy,caseid_type,caseid_no,filed_dd,filed_mon,filed_yyyy,original_court,original_code,...,firstparty_org,secondparty_m,secondparty_f,secondparty_o,legalrep,p_witness,d_witness,custody,other_details,date_today
0,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,NaN,...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
1,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,NaN,...,1.0,1.0,NaN,NaN,No,NaN,1.0,0.0,NaN,2023-04-03
2,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,NaN,...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
3,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,NaN,...,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN,2023-04-03
4,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,NaN,...,1.0,NaN,2.0,NaN,No,NaN,NaN,2.0,NaN,2023-04-03

In [19]:
court_data.insert(0, 'date_today', court_data.pop('date_today'))

In [21]:
court_data = court_data.drop(columns=["date_dd", "date_mon", "date_yyyy"])

In [22]:
court_data.head()

,date_today,caseid_type,caseid_no,filed_dd,filed_mon,filed_yyyy,original_court,original_code,original_number,original_year,...,firstparty_f,firstparty_org,secondparty_m,secondparty_f,secondparty_o,legalrep,p_witness,d_witness,custody,other_details
0,2023-04-03,QRCR,E642,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
1,2023-04-03,QRCR,E1411,31,Oct,2022,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,1.0,0.0,NaN
2,2023-04-03,QRCR,E649,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
3,2023-04-03,QRCR,E638,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,NaN,NaN,No,NaN,NaN,1.0,NaN
4,2023-04-03,QRCRMISC,E109,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,2.0,NaN,No,NaN,NaN,2.0,NaN